[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.28"
evm_version = "paris"
via_ir = true

remappings = [
"@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity",
# "@solady/=lib/solady/src",
]

# [profile.ci]
# fuzz = { runs = 10_000 }

# [profile.default.optimizer_details]
# yul = true

# [profile.default.optimizer_runs]
# # The higher the value of runs the more the optimizer will run. The higher the value of details.yul the more the optimizer will run Yul optimizations.
# # The higher the value of details.yul the more the optimizer will run Yul optimizations.
# # The higher the value of details.yul the more the optimizer will run Yul optimizations.
# # If you want to optimize too much you can use the details.yul = false setting and change the value of runs to 1 or 2 to force the optimizer to run.
# # If you want to optimize too much you can use the details.yul = false setting and change the value of runs to 1 or 2 to force the optimizer to run.
# # For more details see https://docs.soliditylang.org/en/v0.8.17/internals/optimizer.html
# runs = 200
# details = { yul = true, }

# [profile.default.model_checker]
# contracts = { check_storage = true, }
fs_permissions = [{ access = "read-write", path = "./out"}]

[fmt]
line_length = 150
ignore = []

[rpc_endpoints]
sepolia_sanko = "${TESTNET_RPC_URL}"
sanko = "${MAINNET_RPC_URL}"
