[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./out"},{ access = "read", path = "./vrf_proof.json"}]
remappings = [
    "@pythnetwork/entropy-sdk-solidity/=node_modules/@pythnetwork/entropy-sdk-solidity",
    # "@solady/=lib/solady/src",
]

# build
solc = "0.8.28"
evm_version = "paris"
via_ir = true
optimizer = true
optimizer_runs = 200
sparse_mode = true
# details = { yul = true, }
# yul = true
ffi = true
# testing
verbosity = 3
# match-path = "ARB/test/unit/"
# skip=[".t.sol",'.sol']

# ??
# [profile.default.model_checker]
# contracts = { check_storage = true, }

# CI
[profile.ci]
verbosity = 4
# fuzz = { runs = 10_000 }

# formatting
[fmt]
line_length = 150
ignore = []

# networking
[rpc_endpoints]
sepolia_sanko = "${TESTNET_RPC_URL}"
sanko = "${MAINNET_RPC_URL}"
